apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: csit-devhub-seed
spec:
    type: url
    targets:
      - https://github.com/bcgov/csit-connected-services-techdocs/blob/main/catalog-info.yaml
      - https://github.com/bcgov/csit-connected-services-techdocs/blob/APS-4206-nav/getting-started/examples/seed-catalog-info.yaml
